# Generated by Django 2.2.5 on 2020-06-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empoyeeNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
