# Generated by Django 2.2.5 on 2020-06-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200620_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='empoyeeNumber',
            new_name='empoyee_number',
        ),
    ]
