# Generated by Django 2.2.5 on 2020-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_remove_testcase_linked_issues'),
        ('issues', '0003_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='testcases',
            field=models.ManyToManyField(blank=True, to='testcases.Testcase'),
        ),
    ]
