# Generated by Django 2.2.5 on 2020-06-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_issue', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='testcases',
            field=models.ManyToManyField(blank=True, related_name='linked_issue', to='testcases.Testcase'),
        ),
    ]
