# Generated by Django 2.2.5 on 2020-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
