# Generated by Django 2.2.5 on 2020-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_auto_20200621_2219'),
        ('issues', '0002_issue_assignee'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_issues',
            field=models.ManyToManyField(blank=True, to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='project',
            name='testcases',
            field=models.ManyToManyField(blank=True, to='testcases.Testcase'),
        ),
    ]
