# Generated by Django 2.2.5 on 2020-06-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200621_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='linked_issues',
        ),
    ]
