# Generated by Django 2.2.5 on 2020-06-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('projects', '0003_remove_project_linked_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
