# Generated by Django 2.2.5 on 2020-06-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_product_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='capacities',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nand_types',
        ),
        migrations.RemoveField(
            model_name='project',
            name='product_tmp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='soc_types',
        ),
        migrations.AddField(
            model_name='project',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProductType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
