# Generated by Django 2.2.5 on 2020-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200621_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='product_name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='project',
            name='capacities',
            field=models.ManyToManyField(blank=True, to='projects.CapacityType'),
        ),
        migrations.AddField(
            model_name='project',
            name='nand_types',
            field=models.ManyToManyField(blank=True, to='projects.NandType'),
        ),
        migrations.AddField(
            model_name='project',
            name='soc_types',
            field=models.ManyToManyField(blank=True, to='projects.SocType'),
        ),
    ]
