# Generated by Django 2.2.5 on 2020-06-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200621_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product_tmp',
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
