# Generated by Django 2.2.5 on 2020-06-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200621_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
