# Generated by Django 2.2.5 on 2020-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200621_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='testcases',
        ),
    ]
