# Generated by Django 2.2.5 on 2020-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='In progress', max_length=20),
        ),
    ]
