# Generated by Django 2.2.5 on 2020-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcoverages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcoverage',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Warning', 'Warning')], default='Normal', max_length=20),
        ),
    ]
