# Generated by Django 2.2.5 on 2020-07-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcoverages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveragekeytype',
            old_name='group',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='coveragekeytype',
            old_name='sub_group',
            new_name='key_name',
        ),
    ]
