# Generated by Django 2.2.5 on 2020-06-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_auto_20200621_2234'),
        ('projects', '0003_remove_project_linked_issues'),
        ('testcoverages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoverageDataType',
        ),
        migrations.AddField(
            model_name='testcoverage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='testcoverage',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcases.Testcase'),
        ),
    ]
