# Generated by Django 2.2.5 on 2020-06-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='phases',
            field=models.ManyToManyField(blank=True, to='testcases.PhaseType'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='testcases', to='products.Product'),
        ),
    ]
