# Generated by Django 2.2.5 on 2020-07-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_auto_20200702_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='platform',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
