# Generated by Django 2.2.5 on 2020-06-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_auto_20200620_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
