# Generated by Django 2.2.5 on 2020-06-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0004_auto_20200621_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectType',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='projects',
            new_name='products',
        ),
    ]
