# Generated by Django 2.2.5 on 2020-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_auto_20200621_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
