# Generated by Django 2.2.5 on 2020-06-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_auto_20200621_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
