# Generated by Django 2.2.5 on 2020-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_auto_20200622_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='testcases', to='products.Product'),
        ),
    ]
