# Generated by Django 2.2.5 on 2020-06-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('N/A', 'N/A')], default='In progress', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcases.Testcase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
