# Generated by Django 2.2.5 on 2020-07-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testresults', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testresults', to='testcases.Testcase'),
        ),
    ]
